# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
[project]
name = "sop-monitoring"
version = "0.1.0"
description = "A computer vision system for monitoring and analyzing Standard Operating Procedures (SOPs) execution"
readme = "README.md"
authors = [
    {name = "Kiwi Wang", email = "kiwiw@nvidia.com"},
    {name = "Max Huang", email = "maxhuang@nvidia.com"}
]
