######################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
######################################################################################################

version: '3.8'

services:
  ddm-training-microservice:
    image: ${DDM_IMAGE:-ddm_ftms:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DDM_PORT:-32100}:${DDM_PORT:-32100}"
    environment:
      - SERVICE_PORT=${DDM_PORT:-32100}
    volumes:
      - "./ddm:/workspace/sop-ddm-ftms/ddm" 
      - "${CONFIG_DIR:-config}:/workspace/sop-ddm-ftms/assets/config"
      - "${DATASET_ROOT:-data}:/workspace/sop-ddm-ftms/assets/data"
      - "${PRETRAINED_MODEL_ROOT:-pretrained_weights}:/workspace/sop-ddm-ftms/assets/weights"
      - "${RESULTS_ROOT:-results}:/workspace/sop-ddm-ftms/assets/results"
      - "${TOOL_PATH:-tools}:/workspace/sop-ddm-ftms/assets/tools"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    restart: unless-stopped
  metadata_db:
    image: postgres:17.2
    shm_size: 256mb # set shared memory limit when using docker compose
    volumes:
      - ${POSTGRES_DB_ROOT:-postgres_db}:/var/lib/postgresql/data
      - ./db-init-scripts/01-init-tables.sql:/docker-entrypoint-initdb.d/01-init-tables.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sop_db}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS:-64MB}
      POSTGRES_WORK_MEM: ${POSTGRES_WORK_MEM:-4MB}
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always

volumes:
  config:
  data:
  pretrained_weights:
  results:
  tools:
  postgres_db:

