######################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
######################################################################################################


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vlm_aug"
version = "0.0.1"
authors = [
  { name="Leo Liou", email="lliou@nvidia.com" },
]
description = "autolabel_augmenting"
readme = "README.md"
requires-python = ">=3.10"

[tool.hatch.build.targets.sdist]
exclude = [
]

[tool.hatch.build.targets.wheel]
packages = ["vlm_aug/"]

[tool.ruff]
line-length = 119

[tool.ruff.lint]
ignore = ["C901", "E741", "F402", "F823", "E203"]
select = ["C", "E", "F", "I", "W"]

# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.lint.isort]
lines-after-imports = 2
force-single-line = false
known-first-party = ["nvidia_tao_pytorch"]  # Modify this line for your project

[tool.black]
line-length = 119

[tool.isort]
force-single-line = false
