# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
ARG BASE_IMAGE=nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
ARG FFMPEG_VERSION=6.1.1
ARG PYTHON_VERSION=3.12

#========== Build ffmpeg from source ==========#
FROM ${BASE_IMAGE} AS builder
# make this variable available to the build stage
ARG FFMPEG_VERSION

RUN apt-get purge -y cuda-compat-*

# 1. dependencies for building ffmpeg
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        yasm \
        wget \
    && rm -rf /var/lib/apt/lists/*

# 2. download codes
WORKDIR /tmp
RUN wget https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 \
    && tar xjvf ffmpeg-${FFMPEG_VERSION}.tar.bz2

# 3. build ffmpeg
WORKDIR /tmp/ffmpeg-${FFMPEG_VERSION}
RUN ./configure \
      --prefix=/opt/ffmpeg \
      --disable-gpl \
      --disable-nonfree \
      --enable-shared \
      --disable-doc \
      --disable-static \
    && make -j$(nproc) \
    && make install

#========== target image ==========#
FROM ${BASE_IMAGE}
ARG PYTHON_VERSION
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get purge -y cuda-compat-*

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        git \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev \
        python${PYTHON_VERSION}-venv \
        python-is-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

## Create a virtual environment
RUN python${PYTHON_VERSION} -m venv /opt/venv/vlm_service
ENV PATH="/opt/venv/vlm_service/bin:$PATH"

# Copy the compiled FFmpeg from the builder stage
COPY --from=builder /opt/ffmpeg /usr/local

# Configure the dynamic linker to find FFmpeg's shared libraries
RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/ffmpeg.conf \
    && ldconfig

WORKDIR /workspace

# Except for redis, other dependencies are from
# https://github.com/nvidia-cosmos/cosmos-reason1/blob/main/scripts/inference.py
# https://github.com/nvidia-cosmos/cosmos-reason1/blob/main/scripts/inference_vllm.py
# https://github.com/nvidia-cosmos/cosmos-rl/blob/main/Dockerfile
RUN pip install --no-cache-dir \
    redis==6.2.0 \
    accelerate==1.10.0 \
    qwen-vl-utils==0.0.11 \
    transformers==4.55.4 \
    minio==7.2.15 \
    torch==2.8.0 \
    torchvision==0.23.0 \
    torchcodec==0.6 \
    'git+https://github.com/nvidia-cosmos/cosmos-reason1.git@bf43eb078b17c76bdc10866d311c3fec24007238#subdirectory=cosmos_reason1_utils'

# Copy application code
COPY sop_monitoring /workspace/sop_monitoring/sop_monitoring
ENV PYTHONPATH=/workspace/sop_monitoring

CMD ["python", "-m", "sop_monitoring.service.vlm_inference"]
