# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
ARG BASE_IMAGE=sop_inference_bp:vlm_inference_service_1.0.0

FROM ${BASE_IMAGE}
RUN pip install --no-cache-dir pydantic==2.11.7

WORKDIR /worksapce
CMD ["python", "-m", \
     "sop_monitoring.service.action_segment_service", \
     "--redis-stream", \
     "producer_api_server_consumer_action_segment_cr_stream"]
