# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
FROM python:3.13-alpine

# Set working directory
WORKDIR /workspace

# Install Python dependencies
RUN pip install --no-cache-dir \
    gradio==5.38.0 \
    requests==2.32.4 \
    openai==1.97.0

# Copy application code
COPY sop_monitoring /workspace/sop_monitoring/sop_monitoring
ENV PYTHONPATH=/workspace/sop_monitoring
CMD ["python", "-m", "sop_monitoring.client.webapp"]
