#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

name: "ddm"
backend: "python"
# platform: "tensorrt_plan"
max_batch_size: 4
# default_model_filename: "ddm.engine"


dynamic_batching {
    # 5ms
    max_queue_delay_microseconds: 1000
}

input [
  {
    name: "input_0"
    data_type: TYPE_FP32
    # [N, C, SEQ, H, W], [1, 3, 18, x, x]
    dims: [3, -1, ${DS_ACTION_IN_RESOLUTION}, ${DS_ACTION_IN_RESOLUTION} ]
  }
]

output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    # [N, SEQ_BATCH], [1, 8]
    dims: [-1]
  }
]


instance_group [{
    count: 1
    kind: KIND_GPU
    gpus: 0
    }
]

parameters: { key: "FORCE_CPU_ONLY_INPUT_TENSORS" value: {string_value:"no"}}
