# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
systemLog:
  destination: file
  path: "${MONGO_DB_LOG_DIR_IN_CONTAINER}/mongod.log"
  logAppend: true
  quiet: true

net:
  port: ${MONGO_PORT}

storage:
  dbPath: "${MONGO_DB_PATH_IN_CONTAINER}"